import { createContext, useContext, useState, useEffect, ReactNode } from "react";

export type Language = "en" | "ar";

interface LanguageContextType {
  lang: Language;
  toggleLang: () => void;
  t: (key: string) => string;
  isRTL: boolean;
}

// ─── English Translations ────────────────────────────────────────────────────
const en: Record<string, string> = {
  // Nav
  "nav.dashboard": "Dashboard",
  "nav.alerts": "Alerts",
  "nav.cameras": "Cameras",
  "nav.analytics": "Analytics",
  "nav.settings": "Settings",
  "nav.signOut": "Sign Out",
  "nav.edgeDevice": "Edge Device",

  // Header
  "header.subtitle": "Real-time AI security monitoring",
  "header.protected": "Protected",
  "header.allSystemsOnline": "All Systems Online",
  "header.switchLight": "Switch to Light Mode",
  "header.switchDark": "Switch to Dark Mode",

  // Notifications
  "notif.title": "Notifications",
  "notif.markAllRead": "Mark all read",
  "notif.viewAll": "View all alerts",
  "notif.new": "new",
  "notif.cameraOffline": "Camera Back Office went offline",
  "notif.alertResolved": "Alert ALT-003 Resolved",

  // Dashboard
  "dashboard.title": "Security Overview",
  "dashboard.live": "Live",
  "dashboard.totalAlerts": "Total Alerts Today",
  "dashboard.activeCameras": "Active Cameras",
  "dashboard.avgAnomalyScore": "Avg Anomaly Score",
  "dashboard.incidentsResolved": "Incidents Resolved",
  "dashboard.liveAlertFeed": "Live Alert Feed",
  "dashboard.cameraStatus": "Camera Status",
  "dashboard.viewAll": "View all",
  "dashboard.manage": "Manage",
  "dashboard.new": "New",
  "dashboard.offline": "Offline",
  "dashboard.quickActions": "Quick Actions",
  "dashboard.systemHealth": "System Health",
  "dashboard.recentActivity": "Recent Activity",
  "dashboard.reviewNewAlerts": "Review New Alerts",
  "dashboard.viewCameraFeeds": "View Camera Feeds",
  "dashboard.analyticsReport": "Analytics Report",
  "dashboard.systemSettings": "System Settings",
  "dashboard.edgeDeviceCPU": "Edge Device CPU",
  "dashboard.edgeDeviceRAM": "Edge Device RAM",
  "dashboard.storageUsed": "Storage Used",
  "dashboard.networkLatency": "Network Latency",
  "dashboard.alertEscalated": "Alert ALT-003 escalated",
  "dashboard.cameraWentOffline": "Camera CAM-07 went offline",
  "dashboard.alertResolved": "Alert ALT-004 resolved",
  "dashboard.heartbeatOK": "Edge device heartbeat OK",
  "dashboard.dailyReport": "Daily report generated",
  "dashboard.fps": "FPS",
  "dashboard.score": "Score",
  "dashboard.dwell": "Dwell",

  // Alert types
  "alert.loitering": "Loitering Detected",
  "alert.loiteringDetected": "Loitering Detected",
  "alert.suspiciousPose": "Suspicious Pose",
  "alert.suspiciousBehavior": "Suspicious Behavior",
  "alert.unauthorizedAccess": "Unauthorized Access",
  "alert.dwellTime": "Dwell Time",
  "alert.dwellTimeExceeded": "Dwell Time Exceeded",

  // Alert status
  "status.new": "New",
  "status.reviewing": "Reviewing",
  "status.resolved": "Resolved",
  "status.dismissed": "Dismissed",
  "status.active": "Active",
  "status.online": "Online",
  "status.offline": "Offline",

  // Alerts page
  "alerts.title": "Alerts",
  "alerts.filter": "Filter",
  "alerts.search": "Search alerts...",
  "alerts.all": "All",
  "alerts.new": "New",
  "alerts.reviewing": "Reviewing",
  "alerts.resolved": "Resolved",
  "alerts.score": "Score",
  "alerts.dwell": "Dwell",
  "alerts.noAlerts": "No alerts found",
  "alerts.exportCSV": "Export CSV",
  "alerts.id": "Alert ID",
  "alerts.type": "Type",
  "alerts.camera": "Camera",
  "alerts.zone": "Zone",
  "alerts.time": "Time",
  "alerts.status": "Status",
  "alerts.actions": "Actions",

  // Alert detail
  "alertDetail.title": "Alert Detail",
  "alertDetail.back": "Back to Alerts",
  "alertDetail.share": "Share",
  "alertDetail.download": "Download Clip",
  "alertDetail.resolve": "Mark Resolved",
  "alertDetail.incidentType": "Incident Type",
  "alertDetail.camera": "Camera",
  "alertDetail.zone": "Zone",
  "alertDetail.dwellTime": "Dwell Time",
  "alertDetail.anomalyScore": "Anomaly Score",
  "alertDetail.detectedObjects": "Detected Objects",
  "alertDetail.trackId": "Track ID",
  "alertDetail.seconds": "seconds",
  "alertDetail.critical": "Critical",
  "alertDetail.timeline": "Alert Timeline",
  "alertDetail.notes": "Investigation Notes",
  "alertDetail.notesPlaceholder": "Add investigation notes here...",
  "alertDetail.saveNotes": "Save Notes",
  "alertDetail.dwellProgress": "Dwell Time Progress",
  "alertDetail.detectionLog": "Detection Log",
  "alertDetail.personEntered": "Person entered zone",
  "alertDetail.dwellExceeded": "Dwell time exceeded 30s",
  "alertDetail.alertTriggered": "Alert triggered — Loitering detected",
  "alertDetail.subjectMoved": "Subject moved to adjacent zone",
  "alertDetail.alertReviewed": "Alert reviewed by operator",
  "alertDetail.detectedObjectsList": "Detected Objects",
  "alertDetail.person": "Person",
  "alertDetail.backpack": "Backpack",
  "alertDetail.hoodie": "Hoodie",

  // Cameras page
  "cameras.title": "Cameras",
  "cameras.online": "Online",
  "cameras.offline": "Offline",
  "cameras.manage": "Manage",
  "cameras.fps": "FPS",
  "cameras.resolution": "Resolution",
  "cameras.addCamera": "Add Camera",
  "cameras.allCameras": "All Cameras",
  "cameras.onlineOnly": "Online Only",
  "cameras.offlineOnly": "Offline Only",
  "cameras.search": "Search cameras...",
  "cameras.id": "Camera ID",
  "cameras.name": "Name",
  "cameras.zone": "Zone",
  "cameras.status": "Status",
  "cameras.uptime": "Uptime",
  "cameras.actions": "Actions",
  "cameras.viewFeed": "View Feed",
  "cameras.configure": "Configure",
  "cameras.cameraDetails": "Camera Details",
  "cameras.zoneType": "Zone Type",
  "cameras.edgeDevice": "Edge Device",
  "cameras.frameRate": "Frame Rate",
  "cameras.entryZone": "Entry Zone",
  "cameras.productZone": "Product Zone",
  "cameras.restricted": "Restricted",
  "cameras.checkoutZone": "Checkout Zone",
  "cameras.exterior": "Exterior",
  "cameras.staffArea": "Staff Area",

  // Analytics
  "analytics.title": "Analytics",
  "analytics.alertsOverTime": "Alerts Over Time",
  "analytics.alertsByType": "Alerts by Type",
  "analytics.alertsByCamera": "Alerts by Camera",
  "analytics.detectionRate": "Detection Rate",
  "analytics.falsePositiveRate": "False Positive Rate",
  "analytics.avgResponseTime": "Avg Response Time",
  "analytics.today": "Today",
  "analytics.7days": "7 Days",
  "analytics.30days": "30 Days",
  "analytics.totalAlerts": "Total Alerts",
  "analytics.resolvedAlerts": "Resolved Alerts",
  "analytics.falsePositives": "False Positives",
  "analytics.avgScore": "Avg Score",
  "analytics.alerts": "Alerts",
  "analytics.resolved": "Resolved",
  "analytics.fp": "False Positives",
  "analytics.mon": "Mon",
  "analytics.tue": "Tue",
  "analytics.wed": "Wed",
  "analytics.thu": "Thu",
  "analytics.fri": "Fri",
  "analytics.sat": "Sat",
  "analytics.sun": "Sun",

  // Settings
  "settings.title": "Settings",
  "settings.account": "Account",
  "settings.notifications": "Notifications",
  "settings.detection": "Detection Settings",
  "settings.security": "Security",
  "settings.system": "System & Device",
  "settings.general": "General",
  "settings.language": "Language",
  "settings.theme": "Theme",
  "settings.save": "Save Changes",
  "settings.savePreferences": "Save Preferences",
  "settings.fullName": "Full Name",
  "settings.emailAddress": "Email Address",
  "settings.storeName": "Store Name",
  "settings.phoneNumber": "Phone Number",
  "settings.emailNotifications": "Email Notifications",
  "settings.emailNotificationsDesc": "Receive alerts via email",
  "settings.pushNotifications": "Push Notifications",
  "settings.pushNotificationsDesc": "Browser and mobile push alerts",
  "settings.smsAlerts": "SMS Alerts",
  "settings.smsAlertsDesc": "Text message for critical events",
  "settings.criticalAlerts": "Critical Alerts",
  "settings.criticalAlertsDesc": "Score ≥ 85 — always notify",
  "settings.highAlerts": "High Alerts",
  "settings.highAlertsDesc": "Score 70–84",
  "settings.mediumAlerts": "Medium Alerts",
  "settings.mediumAlertsDesc": "Score 55–69",
  "settings.loiteringThreshold": "Loitering Duration Threshold",
  "settings.loiteringThresholdDesc": "Alert when a person stays in a zone longer than this duration",
  "settings.dwellThreshold": "Dwell Time Threshold",
  "settings.dwellThresholdDesc": "Maximum time before dwell alert is triggered",
  "settings.minAnomalyScore": "Minimum Anomaly Score",
  "settings.minAnomalyScoreDesc": "Only generate alerts above this confidence score",
  "settings.changePassword": "Change Password",
  "settings.changePasswordDesc": "Last changed 30 days ago",
  "settings.appVersion": "App Version",
  "settings.lastSync": "Last Sync",
  "settings.justNow": "Just now",
  "settings.connected": "Connected",
  "settings.english": "English",
  "settings.arabic": "Arabic",

  // Login
  "login.title": "Welcome Back",
  "login.subtitle": "Sign in to your BlocKeeper account",
  "login.email": "Email Address",
  "login.password": "Password",
  "login.signIn": "Sign In",
  "login.signingIn": "Signing in...",
  "login.forgotPassword": "Forgot password?",
  "login.emailPlaceholder": "admin@blockeeper.io",
  "login.passwordPlaceholder": "Enter your password",
  "login.fillFields": "Please fill in all fields.",
  "login.aiPowered": "AI-Powered Security",
  "login.realtime": "Real-time monitoring with edge AI",
  "login.version": "BlocKeeper v1.0 · Secure Connection",

  // Mobile
  "mobile.securityStatus": "Security Status",
  "mobile.liveAlerts": "Live Alerts",
  "mobile.cameraGrid": "Camera Grid",
  "mobile.viewAll": "View all",
  "mobile.allClear": "All Clear",
  "mobile.activeThreats": "Active Threats",
  "mobile.criticalAlerts": "Critical Alerts",
  "mobile.systemProtected": "System Protected",
  "mobile.activeAlerts": "Active Alerts",
  "mobile.camerasOnline": "Cameras Online",
  "mobile.todayAlerts": "Today's Alerts",
  "mobile.realTimeAI": "Real-time AI monitoring active",
  "mobile.filterAll": "All",
  "mobile.filterActive": "Active",
  "mobile.filterResolved": "Resolved",
  "mobile.filterDismissed": "Dismissed",
  "mobile.noAlerts": "No alerts in this category",
  "mobile.pushNotifications": "Push Notifications",
  "mobile.pushNotificationsDesc": "Real-time alerts on device",
  "mobile.emailAlerts": "Email Alerts",
  "mobile.emailAlertsDesc": "Daily digest summary",
  "mobile.criticalOnly": "Critical Only",
  "mobile.criticalOnlyDesc": "Only high-severity alerts",
  "mobile.edgeDeviceConnected": "RPi-5-001 · Connected",
  "mobile.lastSync": "Last Sync",
  "mobile.appVersion": "App Version",

  // Filters
  "filter.all": "All",
  "filter.active": "Active",
  "filter.resolved": "Resolved",
  "filter.dismissed": "Dismissed",
  "filter.critical": "Critical",
  "filter.high": "High",
  "filter.medium": "Medium",

  // Severity
  "severity.critical": "Critical",
  "severity.high": "High",
  "severity.medium": "Medium",
  "severity.low": "Low",

  // Alert type keys (short) - new
  "alert.suspicious": "Suspicious Behavior",
  "alert.unauthorized": "Unauthorized Access",
  "alert.dwell": "Dwell Time Exceeded",
  "alert.pose": "Suspicious Pose",

  // Time keys
  "time.2minAgo": "2 min ago",
  "time.18minAgo": "18 min ago",
  "time.1hrAgo": "1 hr ago",
  "time.2hrAgo": "2 hr ago",
  "time.3hrAgo": "3 hr ago",
  "time.5hrAgo": "5 hr ago",
  "time.yesterday": "Yesterday",

  // Status
  "status.secure": "SECURE",

  // Dashboard mobile stats
  "dashboard.activeAlerts": "Active Alerts",
  "dashboard.camerasOnline": "Cameras Online",
  "dashboard.todayIncidents": "Today's Incidents",
  "dashboard.avgResponse": "Avg Response",
  "dashboard.criticalCount": "2 critical",
  "dashboard.offlineCount": "2 offline",
  "dashboard.vsYesterday": "+3 vs yesterday",
  "dashboard.fasterResponse": "-12% faster",
  "dashboard.recentAlerts": "Recent Alerts",
  "dashboard.allSystemsOp": "All systems operational · 10 cameras active",

  // Common actions
  "common.viewAll": "View all",
  "common.manage": "Manage",

  // Alerts actions
  "alerts.found": "alerts found",
  "alerts.resolve": "Resolve",
  "alerts.falsePositive": "False Positive",

  // Cameras
  "cameras.total": "Total",

  // Analytics new keys
  "analytics.lastDays": "Last 7 days",
  "analytics.realtime": "Updated in real-time",
  "analytics.days7": "7 Days",
  "analytics.days30": "30 Days",
  "analytics.export": "Export",
  "analytics.avgResponse": "Avg Response Time",
  "analytics.mostActive": "Most Active Camera",
  "analytics.falsePositive": "False Positive Rate",
  "analytics.alertsByHour": "Alerts by Hour (Today)",
  "analytics.weeklyTrend": "Weekly Alert Trend",
  "analytics.byIncidentType": "By Incident Type",
  "analytics.fpTrend": "False Positive Rate Trend (8 Weeks)",
  "analytics.improving": "Improving",

  // Settings new keys
  "settings.subtitle": "Manage your account and system preferences",
  "settings.accountSettings": "Account Settings",
  "settings.adminAccount": "Admin Account",
  "settings.changeAvatar": "Change avatar",
  "settings.email": "Email Address",
  "settings.phone": "Phone Number",
  "settings.newPassword": "New Password",
  "settings.saved": "Saved successfully",
  "settings.savePrefs": "Save Preferences",
  "settings.saveThresholds": "Save Thresholds",
  "settings.notificationPrefs": "Notification Preferences",
  "settings.channels": "Channels",
  "settings.emailNotif": "Email Notifications",
  "settings.emailNotifDesc": "Receive alerts via email",
  "settings.pushNotif": "Push Notifications",
  "settings.pushNotifDesc": "Browser and mobile push alerts",
  "settings.alertSeverity": "Alert Severity",
  "settings.detectionThresholds": "Detection Thresholds",
  "settings.loiteringDesc": "Alert when a person stays in a zone longer than this duration",
  "settings.dwellDesc": "Maximum time before dwell alert is triggered",
  "settings.anomalyScore": "Minimum Anomaly Score",
  "settings.anomalyDesc": "Only generate alerts above this confidence score",
  "settings.clipRetention": "Video Clip Retention",
  "settings.retentionDesc": "How long to keep recorded alert clips in cloud storage",
  "settings.sec": "sec",
  "settings.outOf100": "/ 100",
  "settings.days": "days",
  "settings.securitySettings": "Security Settings",
  "settings.twoFactor": "Two-Factor Authentication",
  "settings.twoFactorDesc": "Require 2FA for all logins",
  "settings.sessionTimeout": "Session Timeout",
  "settings.sessionTimeoutDesc": "Auto-logout after inactivity",
  "settings.min30": "30 minutes",
  "settings.hour1": "1 hour",
  "settings.hour4": "4 hours",
  "settings.hour8": "8 hours",
  "settings.auditLog": "Audit Log",
  "settings.auditLogDesc": "Track all user actions",
  "settings.ipWhitelist": "IP Whitelist",
  "settings.ipWhitelistDesc": "Restrict access to specific IPs",
  "settings.configure": "Configure",
  "settings.dangerZone": "Danger Zone",
  "settings.dangerDesc": "These actions are irreversible. Proceed with caution.",
  "settings.deleteAccount": "Delete Account",
  "settings.systemDevices": "System & Edge Devices",
  "settings.registeredDevices": "Registered Edge Devices",
  "settings.floor1": "Main Store — Floor 1",
  "settings.floor2": "Main Store — Floor 2",
  "settings.addDevice": "Register New Edge Device",
  "settings.systemInfo": "System Information",
  "settings.aiModel": "AI Model",
  "settings.cameraProtocol": "Camera Protocol",
  "settings.cloudSync": "Cloud Sync",
  "settings.checkUpdates": "Check for Updates",
  "settings.upToDate": "System is up to date",
  "settings.restartDevice": "Restart Device",
  "settings.restarting": "Restarting edge device...",

  // Login new keys
  "login.welcome": "Welcome back",
  "login.tagline": "AI-Powered Security Monitoring",
  "login.signInBtn": "Sign In Securely",
  "login.or": "or",
  "login.noAccount": "Don't have an account?",
  "login.createAccount": "Create account",
  "login.securityNote": "256-bit SSL encryption · Zero-trust architecture",

  // Common
  "common.loading": "Loading...",
  "common.error": "Something went wrong",
  "common.back": "Back",
  "common.close": "Close",
  "common.confirm": "Confirm",
  "common.cancel": "Cancel",
  "common.minAgo": "min ago",
  "common.hrAgo": "hr ago",
  "common.yesterday": "Yesterday",
  "common.sec": "sec",
  "common.ms": "ms",
  "common.online": "Online",
  "common.offline": "Offline",

  // Store Selector
  "store.currentStore": "Current Store",
  "store.allStores": "All Stores",
  "store.allLocations": "All Locations",
  "store.storesCount": "stores",
  "store.switchStore": "Switch Store",
};

// ─── Arabic Translations ──────────────────────────────────────────────────────
const ar: Record<string, string> = {
  // Nav
  "nav.dashboard": "لوحة التحكم",
  "nav.alerts": "التنبيهات",
  "nav.cameras": "الكاميرات",
  "nav.analytics": "التحليلات والإحصاءات",
  "nav.settings": "الإعدادات",
  "nav.signOut": "تسجيل الخروج",
  "nav.edgeDevice": "جهاز المعالجة الطرفية",

  // Header
  "header.subtitle": "منظومة المراقبة الأمنية الذكية",
  "header.protected": "النظام محمي",
  "header.allSystemsOnline": "جميع الأنظمة تعمل بكفاءة",
  "header.switchLight": "تفعيل الوضع الفاتح",
  "header.switchDark": "تفعيل الوضع الداكن",

  // Notifications
  "notif.title": "الإشعارات",
  "notif.markAllRead": "تعليم الكل كمقروء",
  "notif.viewAll": "عرض جميع التنبيهات",
  "notif.new": "جديد",
  "notif.cameraOffline": "كاميرا المستودع الخلفي خارج الخدمة",
  "notif.alertResolved": "تمت معالجة التنبيه ALT-003",

  // Dashboard
  "dashboard.title": "لوحة المراقبة الأمنية",
  "dashboard.live": "بث مباشر",
  "dashboard.totalAlerts": "إجمالي التنبيهات اليوم",
  "dashboard.activeCameras": "الكاميرات المشغّلة",
  "dashboard.avgAnomalyScore": "متوسط درجة الخطورة",
  "dashboard.incidentsResolved": "الحوادث المغلقة",
  "dashboard.liveAlertFeed": "تدفق التنبيهات المباشر",
  "dashboard.cameraStatus": "حالة الكاميرات",
  "dashboard.viewAll": "عرض الكل",
  "dashboard.manage": "إدارة",
  "dashboard.new": "جديد",
  "dashboard.offline": "غير متصل",
  "dashboard.quickActions": "إجراءات سريعة",
  "dashboard.systemHealth": "سلامة النظام",
  "dashboard.recentActivity": "آخر الأحداث",
  "dashboard.reviewNewAlerts": "مراجعة التنبيهات الجديدة",
  "dashboard.viewCameraFeeds": "عرض بث الكاميرات",
  "dashboard.analyticsReport": "تقرير الإحصائيات",
  "dashboard.systemSettings": "ضبط إعدادات النظام",
  "dashboard.edgeDeviceCPU": "استخدام المعالج",
  "dashboard.edgeDeviceRAM": "استخدام الذاكرة",
  "dashboard.storageUsed": "مساحة التخزين المستخدمة",
  "dashboard.networkLatency": "زمن استجابة الشبكة",
  "dashboard.alertEscalated": "تم تصعيد التنبيه ALT-003",
  "dashboard.cameraWentOffline": "انقطعت كاميرا CAM-07 عن الشبكة",
  "dashboard.alertResolved": "تمت معالجة التنبيه ALT-004",
  "dashboard.heartbeatOK": "جهاز المعالجة يعمل بشكل طبيعي",
  "dashboard.dailyReport": "تم إنشاء التقرير اليومي",
  "dashboard.fps": "إطار/ث",
  "dashboard.score": "درجة الخطورة",
  "dashboard.dwell": "مدة التوقف",

  // Alert types
  "alert.loitering": "ترصد شخص مشبوه",
  "alert.loiteringDetected": "رصد شخص متوقف بشكل مريب",
  "alert.suspiciousPose": "وضعية جسد مثيرة للشك",
  "alert.suspiciousBehavior": "سلوك غير طبيعي",
  "alert.unauthorizedAccess": "دخول غير مصرح به",
  "alert.dwellTime": "تجاوز مدة التوقف المسموحة",
  "alert.dwellTimeExceeded": "تجاوز مدة التوقف المسموحة",

  // Alert status
  "status.new": "جديد",
  "status.reviewing": "تحت المراجعة",
  "status.resolved": "تمت المعالجة",
  "status.dismissed": "تم الإغلاق",
  "status.active": "نشط",
  "status.online": "متصل",
  "status.offline": "غير متصل",

  // Alerts page
  "alerts.title": "سجل التنبيهات",
  "alerts.filter": "تصفية",
  "alerts.search": "ابحث في التنبيهات...",
  "alerts.all": "الكل",
  "alerts.new": "جديدة",
  "alerts.reviewing": "تحت المراجعة",
  "alerts.resolved": "معالجة",
  "alerts.score": "درجة الخطورة",
  "alerts.dwell": "مدة التوقف",
  "alerts.noAlerts": "لا توجد تنبيهات للعرض",
  "alerts.exportCSV": "تصدير بصيغة CSV",
  "alerts.id": "رقم التنبيه",
  "alerts.type": "نوع الحادثة",
  "alerts.camera": "الكاميرا",
  "alerts.zone": "المنطقة",
  "alerts.time": "وقت الرصد",
  "alerts.status": "الحالة",
  "alerts.actions": "الإجراءات",

  // Alert detail
  "alertDetail.title": "تفاصيل التنبيه",
  "alertDetail.back": "رجوع إلى سجل التنبيهات",
  "alertDetail.share": "مشاركة",
  "alertDetail.download": "تحميل مقطع الحادثة",
  "alertDetail.resolve": "تأكيد المعالجة",
  "alertDetail.incidentType": "نوع الحادثة",
  "alertDetail.camera": "الكاميرا",
  "alertDetail.zone": "المنطقة",
  "alertDetail.dwellTime": "مدة التوقف",
  "alertDetail.anomalyScore": "درجة خطورة الحادثة",
  "alertDetail.detectedObjects": "العناصر المرصودة",
  "alertDetail.trackId": "رقم التتبع",
  "alertDetail.seconds": "ثانية",
  "alertDetail.critical": "خطر شديد",
  "alertDetail.timeline": "تسلسل أحداث التنبيه",
  "alertDetail.notes": "ملاحظات التحقيق",
  "alertDetail.notesPlaceholder": "سجّل ملاحظاتك حول هذا التنبيه...",
  "alertDetail.saveNotes": "حفظ الملاحظات",
  "alertDetail.dwellProgress": "نسبة تجاوز مدة التوقف",
  "alertDetail.detectionLog": "سجل أحداث الرصد",
  "alertDetail.personEntered": "دخل شخص إلى المنطقة المحمية",
  "alertDetail.dwellExceeded": "تجاوزت مدة التوقف الحد المسموح (30 ثانية)",
  "alertDetail.alertTriggered": "انطلق التنبيه — رصد توقف مشبوه",
  "alertDetail.subjectMoved": "غادر الشخص المنطقة إلى منطقة مجاورة",
  "alertDetail.alertReviewed": "راجع المشغّل التنبيه وأخذ إجراءات",
  "alertDetail.detectedObjectsList": "العناصر المرصودة",
  "alertDetail.person": "شخص",
  "alertDetail.backpack": "حقيبة ظهر",
  "alertDetail.hoodie": "سترة برأس",

  // Cameras page
  "cameras.title": "إدارة الكاميرات",
  "cameras.online": "متصلة",
  "cameras.offline": "غير متصلة",
  "cameras.manage": "إدارة",
  "cameras.fps": "إطار/ث",
  "cameras.resolution": "دقة الصورة",
  "cameras.addCamera": "إضافة كاميرا جديدة",
  "cameras.allCameras": "جميع الكاميرات",
  "cameras.onlineOnly": "المتصلة فقط",
  "cameras.offlineOnly": "غير المتصلة فقط",
  "cameras.search": "ابحث عن كاميرا...",
  "cameras.id": "رقم الكاميرا",
  "cameras.name": "اسم الكاميرا",
  "cameras.zone": "منطقة التغطية",
  "cameras.status": "حالة الاتصال",
  "cameras.uptime": "مدة التشغيل",
  "cameras.actions": "الإجراءات",
  "cameras.viewFeed": "عرض البث المباشر",
  "cameras.configure": "ضبط الإعدادات",
  "cameras.cameraDetails": "معلومات الكاميرا",
  "cameras.zoneType": "نوع منطقة التغطية",
  "cameras.edgeDevice": "جهاز المعالجة",
  "cameras.frameRate": "معدل الإطارات في الثانية",
  "cameras.entryZone": "منطقة المداخل",
  "cameras.productZone": "منطقة المعروضات",
  "cameras.restricted": "منطقة مقيدة الوصول",
  "cameras.checkoutZone": "منطقة الصندوق",
  "cameras.exterior": "محيط خارجي",
  "cameras.staffArea": "منطقة الموظفين",

  // Analytics
  "analytics.title": "التحليلات والتقارير",
  "analytics.alertsOverTime": "تطور التنبيهات عبر الزمن",
  "analytics.alertsByType": "توزيع التنبيهات حسب النوع",
  "analytics.alertsByCamera": "توزيع التنبيهات حسب الكاميرا",
  "analytics.detectionRate": "دقة الكشف",
  "analytics.falsePositiveRate": "نسبة الإنذارات الخاطئة",
  "analytics.avgResponseTime": "متوسط زمن الاستجابة",
  "analytics.today": "اليوم",
  "analytics.7days": "آخر 7 أيام",
  "analytics.30days": "آخر 30 يوماً",
  "analytics.totalAlerts": "إجمالي التنبيهات",
  "analytics.resolvedAlerts": "التنبيهات المعالجة",
  "analytics.falsePositives": "الإنذارات الخاطئة",
  "analytics.avgScore": "متوسط درجة الخطورة",
  "analytics.alerts": "التنبيهات",
  "analytics.resolved": "معالجة",
  "analytics.fp": "إنذارات خاطئة",
  "analytics.mon": "الإثنين",
  "analytics.tue": "الثلاثاء",
  "analytics.wed": "الأربعاء",
  "analytics.thu": "الخميس",
  "analytics.fri": "الجمعة",
  "analytics.sat": "السبت",
  "analytics.sun": "الأحد",

  // Settings
  "settings.title": "ضبط النظام",
  "settings.account": "معلومات الحساب",
  "settings.notifications": "الإشعارات",
  "settings.detection": "إعدادات الكشف",
  "settings.security": "الحماية والأمان",
  "settings.system": "النظام والأجهزة",
  "settings.general": "عام",
  "settings.language": "اللغة",
  "settings.theme": "مظهر الواجهة",
  "settings.save": "حفظ التغييرات",
  "settings.savePreferences": "حفظ التفضيلات",
  "settings.fullName": "الاسم الكامل",
  "settings.emailAddress": "البريد الإلكتروني",
  "settings.storeName": "اسم المنشأة",
  "settings.phoneNumber": "رقم الجوال",
  "settings.emailNotifications": "التنبيهات عبر البريد",
  "settings.emailNotificationsDesc": "استقبال التنبيهات على بريدك الإلكتروني",
  "settings.pushNotifications": "الإشعارات الفورية",
  "settings.pushNotificationsDesc": "إشعارات فورية على المتصفح والجوال",
  "settings.smsAlerts": "التنبيهات عبر الرسائل القصيرة",
  "settings.smsAlertsDesc": "رسائل نصية فورية عند وقوع حوادث خطيرة",
  "settings.criticalAlerts": "تنبيهات الخطر الشديد",
  "settings.criticalAlertsDesc": "درجة الخطورة 85 أو أعلى — إشعار دائم",
  "settings.highAlerts": "تنبيهات الخطورة العالية",
  "settings.highAlertsDesc": "درجة الخطورة بين 70 و 84",
  "settings.mediumAlerts": "تنبيهات الخطورة المتوسطة",
  "settings.mediumAlertsDesc": "درجة الخطورة بين 55 و 69",
  "settings.loiteringThreshold": "حد التوقف المشبوه",
  "settings.loiteringThresholdDesc": "أطلق تنبيهًا عندما يبقى شخص في منطقة محمية أطول من هذه المدة",
  "settings.dwellThreshold": "حد مدة التوقف",
  "settings.dwellThresholdDesc": "أقصى مدة يسمح بها قبل إطلاق تنبيه التوقف",
  "settings.minAnomalyScore": "أدنى درجة خطورة للكشف",
  "settings.minAnomalyScoreDesc": "لا تُطلق تنبيهات إلا للحوادث التي تتجاوز هذه الدرجة",
  "settings.changePassword": "تغيير كلمة المرور",
  "settings.changePasswordDesc": "آخر تغيير قبل 30 يومًا",
  "settings.appVersion": "إصدار التطبيق",
  "settings.lastSync": "آخر مزامنة",
  "settings.justNow": "للتو",
  "settings.connected": "متصل",
  "settings.english": "English",
  "settings.arabic": "العربية",

  // Login
  "login.title": "أهلاً بك مجددًا",
  "login.subtitle": "سجّل دخولك إلى منظومة BlocKeeper",
  "login.email": "البريد الإلكتروني",
  "login.password": "كلمة المرور",
  "login.signIn": "تسجيل الدخول",
  "login.signingIn": "جارٍ التحقق...",
  "login.forgotPassword": "نسيت كلمة المرور؟",
  "login.emailPlaceholder": "admin@blockeeper.io",
  "login.passwordPlaceholder": "أدخل كلمة المرور",
  "login.fillFields": "يرجى ملء جميع الحقول قبل المتابعة.",
  "login.aiPowered": "مراقبة ذكية بتقنية الذكاء الاصطناعي",
  "login.realtime": "كشف فوري للتهديدات عبر معالجة طرفية متقدمة",
  "login.version": "BlocKeeper v1.0 · اتصال مشفّر",

  // Mobile
  "mobile.securityStatus": "حالة المنظومة الأمنية",
  "mobile.liveAlerts": "التنبيهات الحية",
  "mobile.cameraGrid": "عرض الكاميرات",
  "mobile.viewAll": "عرض الكل",
  "mobile.allClear": "لا تهديدات مكتشفة",
  "mobile.activeThreats": "تهديدات نشطة",
  "mobile.criticalAlerts": "تنبيهات خطر شديد",
  "mobile.systemProtected": "النظام يعمل بشكل طبيعي",
  "mobile.activeAlerts": "تنبيهات قيد المعالجة",
  "mobile.camerasOnline": "كاميرات متصلة",
  "mobile.todayAlerts": "تنبيهات اليوم",
  "mobile.realTimeAI": "نظام الكشف الفوري بالذكاء الاصطناعي يعمل",
  "mobile.filterAll": "الكل",
  "mobile.filterActive": "نشطة",
  "mobile.filterResolved": "معالجة",
  "mobile.filterDismissed": "مغلقة",
  "mobile.noAlerts": "لا توجد تنبيهات ضمن هذا التصنيف",
  "mobile.pushNotifications": "الإشعارات الفورية",
  "mobile.pushNotificationsDesc": "إشعارات فورية مباشرة على الجهاز",
  "mobile.emailAlerts": "تنبيهات عبر البريد",
  "mobile.emailAlertsDesc": "ملخص يومي بأبرز التنبيهات",
  "mobile.criticalOnly": "الخطر الشديد فقط",
  "mobile.criticalOnlyDesc": "تنبيهات درجة الخطورة العالية فقط",
  "mobile.edgeDeviceConnected": "RPi-5-001 · متصل بالشبكة",
  "mobile.lastSync": "آخر مزامنة",
  "mobile.appVersion": "إصدار التطبيق",

  // Filters
  "filter.all": "الكل",
  "filter.active": "نشطة",
  "filter.resolved": "معالجة",
  "filter.dismissed": "مغلقة",
  "filter.critical": "خطر شديد",
  "filter.high": "خطورة عالية",
  "filter.medium": "خطورة متوسطة",

  // Severity
  "severity.critical": "خطر شديد",
  "severity.high": "خطورة عالية",
  "severity.medium": "خطورة متوسطة",
  "severity.low": "خطورة منخفضة",

  // Alert type keys (short) - new
  "alert.suspicious": "سلوك غير طبيعي",
  "alert.unauthorized": "دخول غير مصرح به",
  "alert.dwell": "تجاوز مدة التوقف",
  "alert.pose": "وضعية جسد مثيرة للشك",

  // Time keys
  "time.2minAgo": "منذ دقيقتين",
  "time.18minAgo": "منذ 18 دقيقة",
  "time.1hrAgo": "منذ ساعة",
  "time.2hrAgo": "منذ ساعتين",
  "time.3hrAgo": "منذ 3 ساعات",
  "time.5hrAgo": "منذ 5 ساعات",
  "time.yesterday": "أمس",

  // Status
  "status.secure": "النظام آمن",

  // Dashboard mobile stats
  "dashboard.activeAlerts": "تنبيهات قيد المعالجة",
  "dashboard.camerasOnline": "كاميرات متصلة",
  "dashboard.todayIncidents": "حوادث اليوم",
  "dashboard.avgResponse": "متوسط زمن الاستجابة",
  "dashboard.criticalCount": "2 خطر شديد",
  "dashboard.offlineCount": "2 غير متصلة",
  "dashboard.vsYesterday": "+3 مقارنةً بالأمس",
  "dashboard.fasterResponse": "أسرع بنسبة 12%",
  "dashboard.recentAlerts": "آخر التنبيهات",
  "dashboard.allSystemsOp": "جميع الأنظمة تعمل · 10 كاميرات نشطة",

  // Common actions
  "common.viewAll": "عرض الكل",
  "common.manage": "إدارة",

  // Alerts actions
  "alerts.found": "تنبيه مكتشف",
  "alerts.resolve": "تأكيد المعالجة",
  "alerts.falsePositive": "إنذار خاطئ",

  // Cameras
  "cameras.total": "إجمالي الكاميرات",

  // Analytics new keys
  "analytics.lastDays": "آخر 7 أيام",
  "analytics.realtime": "بيانات حية",
  "analytics.days7": "7 أيام",
  "analytics.days30": "30 يومًا",
  "analytics.export": "تصدير التقرير",
  "analytics.avgResponse": "متوسط زمن الاستجابة",
  "analytics.mostActive": "أكثر كاميرا نشاطًا",
  "analytics.falsePositive": "نسبة الإنذارات الخاطئة",
  "analytics.alertsByHour": "توزيع التنبيهات حسب ساعات اليوم",
  "analytics.weeklyTrend": "اتجاه التنبيهات خلال الأسبوع",
  "analytics.byIncidentType": "توزيع حسب نوع الحادثة",
  "analytics.fpTrend": "اتجاه الإنذارات الخاطئة (8 أسابيع)",
  "analytics.improving": "تحسّن مستمر",

  // Settings new keys
  "settings.subtitle": "ضبط بيانات حسابك وتفضيلات النظام",
  "settings.accountSettings": "معلومات الحساب",
  "settings.adminAccount": "حساب المشرف",
  "settings.changeAvatar": "تغيير الصورة الشخصية",
  "settings.email": "البريد الإلكتروني",
  "settings.phone": "رقم الجوال",
  "settings.newPassword": "كلمة مرور جديدة",
  "settings.saved": "تم حفظ التغييرات بنجاح",
  "settings.savePrefs": "حفظ التفضيلات",
  "settings.saveThresholds": "حفظ إعدادات الكشف",
  "settings.notificationPrefs": "إعدادات الإشعارات",
  "settings.channels": "قنوات الإشعار",
  "settings.emailNotif": "التنبيهات عبر البريد",
  "settings.emailNotifDesc": "استقبال التنبيهات على بريدك الإلكتروني",
  "settings.pushNotif": "الإشعارات الفورية",
  "settings.pushNotifDesc": "إشعارات فورية على المتصفح والجوال",
  "settings.alertSeverity": "درجة خطورة التنبيه",
  "settings.detectionThresholds": "عتبات الكشف",
  "settings.loiteringDesc": "أطلق تنبيهًا عندما يبقى شخص في منطقة محمية أطول من هذه المدة",
  "settings.dwellDesc": "أقصى مدة يسمح بها قبل إطلاق تنبيه التوقف",
  "settings.anomalyScore": "أدنى درجة خطورة للكشف",
  "settings.anomalyDesc": "لا تُطلق تنبيهات إلا للحوادث التي تتجاوز هذه الدرجة",
  "settings.clipRetention": "مدة حفظ مقاطع الحوادث",
  "settings.retentionDesc": "مدة الاحتفاظ بمقاطع التنبيهات المسجّلة في التخزين السحابي",
  "settings.sec": "ثانية",
  "settings.outOf100": "/ 100",
  "settings.days": "يومًا",
  "settings.securitySettings": "الحماية والأمان",
  "settings.twoFactor": "التحقق بخطوتين",
  "settings.twoFactorDesc": "اشتراط التحقق بخطوتين عند كل تسجيل دخول",
  "settings.sessionTimeout": "مدة انتهاء الجلسة",
  "settings.sessionTimeoutDesc": "تسجيل خروج تلقائي بعد فترة خمول",
  "settings.min30": "30 دقيقة",
  "settings.hour1": "ساعة واحدة",
  "settings.hour4": "4 ساعات",
  "settings.hour8": "8 ساعات",
  "settings.auditLog": "سجل الأحداث",
  "settings.auditLogDesc": "تتبع جميع إجراءات المستخدمين",
  "settings.ipWhitelist": "عناوين IP المعتمدة",
  "settings.ipWhitelistDesc": "تقييد الوصول لعناوين IP محددة فقط",
  "settings.configure": "ضبط الإعدادات",
  "settings.dangerZone": "منطقة الإجراءات الحرجة",
  "settings.dangerDesc": "هذه الإجراءات نهائية ولا يمكن التراجع عنها. تابع بحذر شديد.",
  "settings.deleteAccount": "حذف الحساب نهائيًا",
  "settings.systemDevices": "النظام وأجهزة المعالجة",
  "settings.registeredDevices": "أجهزة المعالجة المسجّلة",
  "settings.floor1": "الفرع الرئيسي — الدور الأول",
  "settings.floor2": "الفرع الرئيسي — الدور الثاني",
  "settings.addDevice": "إضافة جهاز معالجة جديد",
  "settings.systemInfo": "معلومات النظام",
  "settings.aiModel": "نموذج الذكاء الاصطناعي المستخدم",
  "settings.cameraProtocol": "بروتوكول الكاميرات",
  "settings.cloudSync": "المزامنة مع السحابة",
  "settings.checkUpdates": "التحقق من وجود تحديثات",
  "settings.upToDate": "النظام محدّث بالكامل",
  "settings.restartDevice": "إعادة تشغيل جهاز المعالجة",
  "settings.restarting": "جارٍ إعادة تشغيل جهاز المعالجة...",

  // Login new keys
  "login.welcome": "أهلاً بك مجددًا",
  "login.tagline": "منظومة المراقبة الأمنية الذكية",
  "login.signInBtn": "دخول آمن",
  "login.or": "أو",
  "login.noAccount": "ليس لديك حساب بعد؟",
  "login.createAccount": "إنشاء حساب جديد",
  "login.securityNote": "تشفير 256-بت · بنية عدم الثقة",

  // Common
  "common.loading": "جارٍ التحميل...",
  "common.error": "حدث خطأ، يرجى المحاولة مجددًا",
  "common.back": "رجوع",
  "common.close": "إغلاق",
  "common.confirm": "تأكيد",
  "common.cancel": "إلغاء",
  "common.minAgo": "د. مضت",
  "common.hrAgo": "س. مضت",
  "common.yesterday": "أمس",
  "common.sec": "ثانية",
  "common.ms": "مللي ثانية",
  "common.online": "متصل",
  "common.offline": "غير متصل",

  // Store Selector
  "store.currentStore": "الفرع الحالي",
  "store.allStores": "جميع الفروع",
  "store.allLocations": "جميع المواقع",
  "store.storesCount": "فروع",
  "store.switchStore": "تغيير الفرع",
};

const translations: Record<Language, Record<string, string>> = { en, ar };

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLang] = useState<Language>(() => {
    return (localStorage.getItem("bk_lang") as Language) || "en";
  });

  const isRTL = lang === "ar";

  useEffect(() => {
    localStorage.setItem("bk_lang", lang);
    document.documentElement.setAttribute("dir", isRTL ? "rtl" : "ltr");
    document.documentElement.setAttribute("lang", lang);
    if (isRTL) {
      document.documentElement.style.fontFamily = "'Cairo', 'Tajawal', 'Segoe UI', sans-serif";
    } else {
      document.documentElement.style.fontFamily = "";
    }
  }, [lang, isRTL]);

  const toggleLang = () => setLang(l => (l === "en" ? "ar" : "en"));

  const t = (key: string): string => {
    return translations[lang][key] ?? translations["en"][key] ?? key;
  };

  return (
    <LanguageContext.Provider value={{ lang, toggleLang, t, isRTL }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error("useLanguage must be used within LanguageProvider");
  return ctx;
}
